import boardMockData from '../../mocks/board.js';

const lists = boardMockData.lists;
const numberOfLists = lists.length;

// Code Structure below of the test generated by chatgpt and seems enough so it was modified to fit the exact mock data information and to use the custom command

describe('Project Management Board E2e', () => {
	beforeEach(() => {
		cy.visit('/');
	});

	it('should display the board with lists and cards', () => {
		cy.get('h1').contains('Project Management Board').should('be.visible');

		cy.getByCy('list.container').should('have.length', numberOfLists);

		// Loop through each list and verify if it contains cards
		cy.getByCy('list.container').each((list, index) => {
			const listTitle = lists[index].name;
			const listCards = lists[index].cards;

			// Check if the list title is visible
			cy.wrap(list)
				.find('[data-cy="list.title"]')
				.should('be.visible')
				.contains(listTitle, { matchCase: false });

			// Check if the list contains at least one card
			cy.wrap(list)
				.find('[data-cy="card.container"]')
				.should('have.length', listCards.length);

			// Verify that card titles are visible
			cy.wrap(list)
				.find('[data-cy="card.title"]')
				.each((card, cardIndex) => {
					cy.wrap(card)
						.should('be.visible')
						.contains(listCards[cardIndex].title, { matchCase: false });
				});
		});
	});
});
