const projectBoard = {
	disclaimer: 'data example initially generated by chatgpt',
	id: '1',
	name: 'Project Management Board',
	description: 'This board is used for managing tasks',
	createdAt: '2024-10-08T12:00:00Z',
	updatedAt: '2024-10-08T12:30:00Z',
	lists: [
		{
			id: 'EuQktZvAr9',
			name: 'To-Do',
			position: 1,
			cards: [
				{
					id: 'todo-1',
					title: 'Set up project structure',
					description:
						'Initialize the project with the necessary dependencies and configurations.',
					labels: ['setup', 'priority-high'],
					dueDate: '2024-10-10T23:59:00Z',
					checklist: [
						{
							id: 'check-1',
							text: 'Create folder structure',
							isChecked: true,
						},
						{
							id: 'check-2',
							text: 'Install dependencies',
							isChecked: false,
						},
					],
					comments: [
						{
							id: 'comment-1',
							user: 'Jane Doe',
							text: 'We should consider using Vite for better performance.',
							createdAt: '2024-10-08T13:00:00Z',
						},
					],
					isArchived: false,
					attachments: [
						{
							id: 'att-1',
							filename: 'project_structure.png',
							url: 'https://example.com/project_structure.png',
						},
					],
				},
				{
					id: 'todo-2',
					title: 'Design UI for the app',
					description: 'Create wireframes and a UI mockup for the main pages.',
					labels: ['design', 'priority-medium'],
					dueDate: '2024-10-12T23:59:00Z',
					checklist: [],
					comments: [],
					isArchived: false,
					attachments: [],
				},
			],
		},
		{
			id: 'WFLThPFZHy',
			name: 'Doing',
			position: 2,
			cards: [
				{
					id: 'todo-3',
					title: 'Build Task Management UI',
					description: 'Develop the frontend UI for adding and managing tasks.',
					labels: ['frontend', 'priority-high'],
					dueDate: '2024-10-15T23:59:00Z',
					checklist: [
						{
							id: 'check-3',
							text: 'Set up UI components',
							isChecked: true,
						},
						{
							id: 'check-4',
							text: 'Connect API to frontend',
							isChecked: false,
						},
					],
					comments: [
						{
							id: 'comment-2',
							user: 'John Smith',
							text: "Don't forget to handle error states.",
							createdAt: '2024-10-08T14:00:00Z',
						},
					],
					isArchived: false,
					attachments: [
						{
							id: 'att-2',
							filename: 'task_ui_sketch.pdf',
							url: 'https://example.com/task_ui_sketch.pdf',
						},
					],
				},
			],
		},
		{
			id: 'n_TJt4-3w8',
			name: 'Done',
			position: 3,
			cards: [
				{
					id: 'todo-4',
					title: 'Set up GitHub repo',
					description: 'Initialize the project repository on GitHub.',
					labels: ['setup', 'priority-low'],
					dueDate: '2024-10-05T23:59:00Z',
					checklist: [
						{
							id: 'check-5',
							text: 'Create repository',
							isChecked: true,
						},
						{
							id: 'check-6',
							text: 'Add README file',
							isChecked: true,
						},
					],
					comments: [
						{
							id: 'comment-3',
							user: 'Jane Doe',
							text: 'Repo is live, please clone it.',
							createdAt: '2024-10-06T10:00:00Z',
						},
					],
					isArchived: false,
					attachments: [
						{
							id: 'att-3',
							filename: 'repo_link.txt',
							url: 'https://github.com/example/project',
						},
					],
				},
			],
		},
	],
};

export default projectBoard;
